#!/bin/bash
# Coded by MitRax
# Init
FILE="/tmp/out.$$"
GREP="/bin/grep"
#....
# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi


figlet -f slant 'BURPY' && figlet -f digital  " Coded by MitRax" 
figlet -f digital  "Installing Java" 
apt install openjdk-17-jdk -y 
figlet -f digital  "Java Installed " 
clear
figlet -f digital  "Creating Directory " 
mkdir /opt/BURPY
sleep 2
figlet -f digital  "Directory Created " 
clear
figlet -f digital  "Moving Files In Directory"
mv burpy-loader.jar /opt/BURPY/
mv burp-suite-professional.svg /usr/share/pixmaps/
mv burpsuite_pro_v* /opt/BURPY/
sleep 5
figlet -f digital  "Files Moved In Directory" 
clear
figlet -f digital  "Writing Executable Commands" 
echo "cd /opt/BURPY/ && java -jar burpy-loader.jar" > /bin/burpy-loader
chmod +x /bin/burpy-loader
figlet -f digital  "Executable Commands as Been Written" 
clear 
figlet -f slant  "BURPY"  && figlet -f digital "Has Been Installed In Your System"
exit









